export const allApps = [
   {
      rank: 1,
      name: "Uu Rummy",
      slug: "uu-rummy",
      icon: "/uu-rummy-app-icon-green.jpg",
      downloads: "2.2M+",
      bonus: "₹206",
      minWithdrawal: "₹200",
      description: "UU Rummy Tournament - Win ₹50,000 Weekly Cash Prize",
      rating: 5,
   },
   {
      rank: 2,
      name: "Bappa Rummy",
      slug: "uu-rummy",
      icon: "/bappa-rummy-app-icon-orange.jpg",
      downloads: "135K+",
      bonus: "₹540",
      minWithdrawal: "₹200",
      description: "Bappa Rummy App, Play & Win ₹3500+ Real Cash Daily",
      rating: 4,
   },
   {
      rank: 3,
      name: "Rummy West",
      slug: "uu-rummy",
      icon: "/rummy-west-app-icon-brown.jpg",
      downloads: "224K+",
      bonus: "₹51",
      minWithdrawal: "₹100",
      description: "Rummy West – Classic Indian Rummy Game",
      rating: 4,
   },
   {
      rank: 4,
      name: "Rummy Alliance",
      slug: "uu-rummy",
      icon: "/rummy-alliance-app-icon-red.jpg",
      downloads: "265K+",
      bonus: "₹75",
      minWithdrawal: "₹100",
      description:
         "Join Rummy Alliance Now - Exciting Tournaments & Big Rewards",
      rating: 5,
   },
   {
      rank: 5,
      name: "Rummy Rafale",
      slug: "uu-rummy",
      icon: "/rummy-rafale-app-icon-blue.jpg",
      downloads: "0",
      bonus: "₹25",
      minWithdrawal: "₹400",
      description: "Rummy Rafale: India's Most Exciting Rummy Game",
      rating: 4,
   },
   {
      rank: 6,
      name: "Spin Rummy",
      slug: "uu-rummy",
      icon: "/spin-rummy-app-icon-green-wheel.jpg",
      downloads: "1.7M+",
      bonus: "₹41",
      minWithdrawal: "₹300",
      description: "Spin Rummy Online - Withdraw from ₹100",
      rating: 4,
   },
];
