const siteMetadata = {
  title: 'Download Rummy Gamer 2025 – All Rummy Games & Teen Patti with ₹1000 Bonus',
  author: 'Rummy Gamer',
  description: 'Play Rummy 51, Teen Patti, and Indian Rummy on Rummy Gamer App 2025. Get ₹1000 signup bonus, instant withdrawals, and safe real cash games.',
  language: 'en-IN',
  theme: 'system',
  siteUrl: 'https://rummygamer.com', // your real domain
  siteLogo: '/logo.png',
  socialBanner: '/logo.png',
  email: 'support@rummygamer.com',
  facebook: 'https://facebook.com/rummygamer',
  youtube: 'https://www.youtube.com/@rummygamer',
  locale: 'en-IN',
  keywords: [
    'rummy',
    'rummy 51',
    'all rummy apps',
    'rummy all games',
    'bonus rummy',
    'all rummy games',
    'rummy new app',
    'all rummy apk',
    'new rummy apk',
    'indian rummy',
    'rummy game apk',
    'rummy download',
    'bonus wala game',
    'new rummy',
    '7 rummy',
    'junglee rummy',
    'rummy 50 rupees free download',
    'free online rummy 13 card game',
    'free signup bonus casino india',
    'play india satta',
    'satta tiger',
    'satta rs'
  ],
};

export default siteMetadata;
